### ISSUE TITLE
"./configure --with-mysql=/usr/include/mysql/" fails with "configure: error: Invalid MySQL directory - unable to find mysql.h under /usr/include/mysql/" although "/usr/include/mysql/mysql.h" is present

### ISSUE THREAD

**Issue by krichter722** [Maxime2/dataparksearch#11]
```
$ stat /usr/include/mysql/mysql.h 
  File: '/usr/include/mysql/mysql.h'
  Size: 29172       Blocks: 64         IO Block: 4096   regular file
Device: 16h/22d Inode: 5569333     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-05-13 10:57:03.228144358 +0200
Modify: 2016-03-28 20:06:12.000000000 +0200
Change: 2016-05-04 11:08:00.626872422 +0200
 Birth: -
```

experienced with 9257ced

**Comment by Maxime2** [comment]
If it is standard MySQL location as it looks like it should work with
./configure --with-mysql

otherwise you need to point to top of the location:
./configure --with-mysql=/usr

**Comment by krichter722** [comment]
Now I get it. May I suggest to change

      --with-mysql=DIR      Include MySQL support.  DIR is the MySQL base
                              install directory, default is to search through
                              a number of common places for the MySQL files.

to 

      --with-mysql[=DIR]      Include MySQL support.  DIR is the MySQL installation prefix (e.g. `/usr`),
                              omitting DIR triggers a search through
                              a number of common places for the MySQL files.

because "base install directory" is hard to get, especially with the error message referring to `mysql.h` when `configure` wants `include/mysql/mysql.h`. Definitely useful to add an example no matter how `DIR` is called.

**Comment by ericfranzee** [comment]
You need to install the MySQL development files.

#sudo apt-get install mysql-devel
or
#sudo yum install mysql-devel

**Comment by itJunky** [comment]
What if i want to use Percona or MariaDB?

**Comment by sburn** [comment]
> What if i want to use Percona or MariaDB?

Will work. Just make sure to client libs are in place.

**Comment by itJunky** [comment]
configure: error: Invalid MySQL directory - unable to find mysql.h under /usr/include/mariadb/mysql.h

# ls -l /usr/include/mariadb/mysql.h
-rw-r--r-- 1 root root 41230 ноя  5 22:40 /usr/include/mariadb/mysql.h
