### ISSUE TITLE
"make bin-dist" fails due to "tar: invalid option -- 'y'"

### ISSUE THREAD

**Issue by krichter722** [Maxime2/dataparksearch#8]
see https://travis-ci.org/krichter722/dataparksearch/builds/132482170 for details

**Comment by Maxime2** [comment]
Just out of curiosity, what version of Linux is used here?
As the tar in Ubuntu Linux has -y option supported.

**Comment by krichter722** [comment]
> Just out of curiosity, what version of Linux is used here?

12.04 which is quite old, but it'd be nice if a test was added to `configure` in order to fail more verbosely and earlier. You can find more information about the OS in the collapsed first lines of output provided at the linked log.

**Comment by Maxime2** [comment]
I have added checking for tar flags enabling bzip2 compression, that solves this issue.
Thank you for reporting!
